apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"addresses":["3.91.252.145"],"port":31693,"protocol":"TCP","serviceName":"angularns:angulardeploy-nodeport","allNodes":true}]'
    field.cattle.io/targetWorkloadIds: '["angularns/angulardeploy"]'
    management.cattle.io/ui-managed: "true"
  creationTimestamp: "2022-05-08T02:22:08Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:field.cattle.io/publicEndpoints: {}
          f:field.cattle.io/targetWorkloadIds: {}
          f:management.cattle.io/ui-managed: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"c82f2b2e-dd91-4007-9a61-2f7644f4cd00"}: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:internalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":4200,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: agent
    operation: Update
    time: "2022-05-08T02:22:08Z"
  name: angulardeploy-nodeport
  namespace: angularns
  ownerReferences:
  - apiVersion: apps/v1
    controller: true
    kind: Deployment
    name: angulardeploy
    uid: c82f2b2e-dd91-4007-9a61-2f7644f4cd00
  resourceVersion: "1892"
  uid: 08647b33-a902-4fbc-8d1f-bda779725804
spec:
  clusterIP: 10.43.21.104
  clusterIPs:
  - 10.43.21.104
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: angularnp
    nodePort: 31693
    port: 4200
    protocol: TCP
    targetPort: 4200
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-angularns-angulardeploy
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
