apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"addresses":["3.91.100.164"],"port":31568,"protocol":"TCP","serviceName":"hw3ns:hw3deployment-nodeport","allNodes":true}]'
    field.cattle.io/targetWorkloadIds: '["hw3ns/hw3deployment"]'
    management.cattle.io/ui-managed: "true"
  creationTimestamp: "2022-05-08T01:33:20Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:field.cattle.io/publicEndpoints: {}
          f:field.cattle.io/targetWorkloadIds: {}
          f:management.cattle.io/ui-managed: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"5f7e423a-8628-4be8-a215-7ed6c23a2795"}: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:internalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":8080,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: agent
    operation: Update
    time: "2022-05-08T01:33:20Z"
  name: hw3deployment-nodeport
  namespace: hw3ns
  ownerReferences:
  - apiVersion: apps/v1
    controller: true
    kind: Deployment
    name: hw3deployment
    uid: 5f7e423a-8628-4be8-a215-7ed6c23a2795
  resourceVersion: "1743"
  uid: 50be6d56-4c9a-4f2f-8f89-27f54fc22e15
spec:
  clusterIP: 10.43.207.161
  clusterIPs:
  - 10.43.207.161
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: hw3np
    nodePort: 31568
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-hw3ns-hw3deployment
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
