apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["swe645hw/swe645deployment"]'
    management.cattle.io/ui-managed: "true"
  creationTimestamp: "2022-04-07T01:03:47Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:field.cattle.io/targetWorkloadIds: {}
          f:management.cattle.io/ui-managed: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"b1c63c01-d0e9-4225-b139-eef8a8b5bebf"}: {}
      f:spec:
        f:internalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":8080,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: agent
    operation: Update
    time: "2022-04-07T01:03:47Z"
  name: swe645deployment
  namespace: swe645hw
  ownerReferences:
  - apiVersion: apps/v1
    controller: true
    kind: Deployment
    name: swe645deployment
    uid: b1c63c01-d0e9-4225-b139-eef8a8b5bebf
  resourceVersion: "3638"
  uid: 30fa80ea-f420-47e7-ac02-cedb2ae99fc1
spec:
  clusterIP: 10.43.210.73
  clusterIPs:
  - 10.43.210.73
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: lb-port
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-swe645hw-swe645deployment
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
